### PR TITLE
	Update of the FRENCH translation for the OneAll Social Login extension

### PR DESCRIPTION
**Pull request by Galixte**
Hi @SchlesserClaude,

could you merge this, please ?

### CODE REVIEW

**Comment by SchlesserClaude** [comment]
Thank you very much! As it took a while for me to merge it, the branch had conflicts. I have manually added the changes. Best Regards,

**Comment by Galixte** [comment]
Thanks @SchlesserClaude!

**Comment by Galixte** [comment]
It’s not my translation, a lot of sentence were written with a bad way or non-sense.

**Comment by SchlesserClaude** [comment]
Sorry! That was not intended. We in fact renamed your translation "passerelle de connexion" to "Social Login", as this is the name of the service and we changed some translations, as we also updated the english. I will have a closer look!

**Comment by Galixte** [comment]
I will ;)

**Pull request closed without merging**
